"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuthStore } from "@/stores/authStore";
import { useCVStore } from "@/stores/cvStore";
import PageHeader from "@/components/my-cvs/PageHeader";
import DeleteConfirmationDialog from "@/components/my-cvs/DeleteConfirmationDialog";
import LoadingPage from "@/components/LoadingPage";
import { mockCVs } from "@/services/mockData";
import UserCVsSection from "@/components/my-cvs/UserCVsSection";
import TemplateCVsSection from "@/components/my-cvs/TemplateCVsSection";
import { EPrivacy } from "@/types/enum";

export default function MyCVsPage() {
  const { userAuth } = useAuthStore();
  const {
    handleSetCurrentCV,
    handleSetCurrentStep,
    deleteCV,
    duplicateCV,
    getUserCVs,
    getAllCVs,
    handleGeneratePDF,
  } = useCVStore();

  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [cvList, setCVlist] = useState<ICV[]>([]);
  const [templateCVs, setTemplateCVs] = useState<ICV[]>([]);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [cvToDelete, setCvToDelete] = useState<string | null>(null);

  useEffect(() => {
    loadCVs();
    // Load template CVs on mount
    setTemplateCVs(mockCVs);
  }, [userAuth, router]);

  const loadCVs = async () => {
    if (!userAuth) return;

    setLoading(true);

    const response = await getUserCVs(userAuth.id);
    if (response?.data) {
      // const cvs = response.data.cvs || [];
      // setCVlist(cvs);
      setCVlist([]); // Show empty for now, will show user's actual CVs when backend ready
    }

    setLoading(false);
  };

  const loadTemplateCVs = async () => {
    const response = await getAllCVs();
    if (response?.data) {
      const allCvs = response.data.cvs || [];
      // setTemplateCVs(allCvs);
      setTemplateCVs(mockCVs); // Temporary: using mockCVs, replace with allCvs when backend ready
    }
  };

  const handleCreateNew = () => {
    handleSetCurrentCV(null);
    handleSetCurrentStep(0);
    router.push("/cv-builder");
  };

  const handleEdit = (cv: ICV) => {
    handleSetCurrentCV(cv);
    handleSetCurrentStep(0);
    router.push("/cv-builder");
  };

  const handleDeleteClick = (cvId: string) => {
    setCvToDelete(cvId);
    setDeleteDialogOpen(true);
  };

  const handleDeleteConfirm = async () => {
    if (!cvToDelete) return;

    deleteCV(cvToDelete);
  };

  const handleDuplicate = (cvId: string) => {
    duplicateCV(cvId);
  };

  const handleDuplicateTemplate = async (cv: ICV) => {
    // Clone CV and add "CV của tôi" to title
    const newTitle = `${cv.title} - CV của tôi`;
    const newCV: ICV = {
      ...cv,
      id: "", // Will be generated by backend
      userId: userAuth?.id,
      title: newTitle,
      privacy: EPrivacy.PRIVATE, // Default to private for user's copy
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    handleSetCurrentCV(newCV);
    router.push("/cv-builder");
  };

  if (!userAuth) {
    return null;
  }

  if (loading) {
    return <LoadingPage />;
  }

  return (
    <div className="min-h-screen flex items-center justify-center py-12">
      <div className="container max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col gap-8">
          <PageHeader onCreateNew={handleCreateNew} />

          <UserCVsSection
            cvList={cvList}
            onCreateNew={handleCreateNew}
            onEdit={handleEdit}
            onDuplicate={handleDuplicate}
            onDelete={handleDeleteClick}
          />

          <TemplateCVsSection
            templateCVs={templateCVs}
            onDuplicateTemplate={handleDuplicateTemplate}
            onDownload={handleGeneratePDF}
          />
        </div>
      </div>

      <DeleteConfirmationDialog
        open={deleteDialogOpen}
        onOpenChange={setDeleteDialogOpen}
        onConfirm={handleDeleteConfirm}
      />
    </div>
  );
}
