package com.example.cvservice.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CVDto {
    private UUID id;
    private String title;
    private PersonalInfoDto personalInfo;
    private List<ExperienceDto> experience;
    private List<EducationDto> education;
    private List<String> skills;
    private String createdAt;
    private String updatedAt;

    // Getters and setters are generated by Lombok
}
