import { EUserRole, EUserStatus, EAISuggestionType, EPrivacy } from "@/types/enum";

// Mock Users Data
export const mockUsers: IUser[] = [
    {
        id: "user-1",
        username: "johndoe",
        email: "john.doe@example.com",
        fullname: "John Doe",
        avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
    },
    {
        id: "user-2",
        username: "janesmith",
        email: "jane.smith@example.com",
        fullname: "Jane Smith",
        avatarUrl: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
    },
    {
        id: "user-3",
        username: "mikejohnson",
        email: "mike.johnson@example.com",
        fullname: "Mike Johnson",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.ADMIN,
        status: EUserStatus.ACTIVE,
    },
    {
        id: "user-4",
        username: "sarahwilson",
        email: "sarah.wilson@example.com",
        fullname: "Sarah Wilson",
        avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
    },
    {
        id: "user-5",
        username: "davidbrown",
        email: "david.brown@example.com",
        fullname: "David Brown",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.PENDING,
    },
    {
        id: "user-6",
        username: "emilydavis",
        email: "emily.davis@example.com",
        fullname: "Emily Davis",
        avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
    },
    {
        id: "user-7",
        username: "alexgarcia",
        email: "alex.garcia@example.com",
        fullname: "Alex Garcia",
        avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
    },
    {
        id: "user-8",
        username: "lisachen",
        email: "lisa.chen@example.com",
        fullname: "Lisa Chen",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
    },
    {
        id: "user-9",
        username: "robertlee",
        email: "robert.lee@example.com",
        fullname: "Robert Lee",
        avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.BANNED,
    },
    {
        id: "user-10",
        username: "amandataylor",
        email: "amanda.taylor@example.com",
        fullname: "Amanda Taylor",
        avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
    },
];

// Mock Personal Info Data
export const mockPersonalInfos: IPersonalInfo[] = [
    {
        id: "personal-1",
        fullname: "John Doe",
        email: "john.doe@example.com",
        phone: "john.doe@example.com",
        location: "New York, NY",
        summary: "Experienced software developer with 5+ years in full-stack development, specializing in React and Node.js.",
        avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "john-doe-avatar-123",
    },
    {
        id: "personal-2",
        fullname: "Jane Smith",
        email: "jane.smith@example.com",
        phone: "+1-555-0124",
        location: "San Francisco, CA",
        summary: "Creative UI/UX designer with a passion for user-centered design and modern web technologies.",
        avatarUrl: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "jane-smith-avatar-456",
    },
    {
        id: "personal-3",
        fullname: "Mike Johnson",
        email: "mike.johnson@example.com",
        phone: "+1-555-0125",
        location: "Austin, TX",
        summary: "DevOps engineer focused on cloud infrastructure, CI/CD pipelines, and scalable system architecture.",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "mike-johnson-avatar-789",
    },
    {
        id: "personal-4",
        fullname: "Sarah Wilson",
        email: "sarah.wilson@example.com",
        phone: "+1-555-0126",
        location: "Seattle, WA",
        summary: "Product manager with expertise in agile methodologies and cross-functional team leadership.",
        avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "sarah-wilson-avatar-101",
    },
    {
        id: "personal-5",
        fullname: "David Brown",
        email: "david.brown@example.com",
        phone: "+1-555-0127",
        location: "Chicago, IL",
        summary: "Data scientist specializing in machine learning, statistical analysis, and business intelligence.",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "david-brown-avatar-202",
    },
    {
        id: "personal-6",
        fullname: "Emily Davis",
        email: "emily.davis@example.com",
        phone: "+1-555-0128",
        location: "Boston, MA",
        summary: "Marketing specialist with expertise in digital campaigns, SEO, and content strategy.",
        avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "emily-davis-avatar-303",
    },
    {
        id: "personal-7",
        fullname: "Alex Garcia",
        email: "alex.garcia@example.com",
        phone: "+1-555-0129",
        location: "Miami, FL",
        summary: "Full-stack developer with strong foundation in both frontend and backend technologies.",
        avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "alex-garcia-avatar-404",
    },
    {
        id: "personal-8",
        fullname: "Lisa Chen",
        email: "lisa.chen@example.com",
        phone: "+1-555-0130",
        location: "Los Angeles, CA",
        summary: "UX researcher focused on user behavior analysis and usability testing methodologies.",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "lisa-chen-avatar-505",
    },
    {
        id: "personal-9",
        fullname: "Robert Lee",
        email: "robert.lee@example.com",
        phone: "+1-555-0131",
        location: "Denver, CO",
        summary: "Cybersecurity specialist with expertise in threat analysis and network security.",
        avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "robert-lee-avatar-606",
    },
    {
        id: "personal-10",
        fullname: "Amanda Taylor",
        email: "amanda.taylor@example.com",
        phone: "+1-555-0132",
        location: "Portland, OR",
        summary: "Project manager with proven track record in delivering complex software projects on time.",
        avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
        avatarPublicId: "amanda-taylor-avatar-707",
    },
];

// Mock Experiences Data
export const mockExperiences: IExperience[] = [
    {
        id: "exp-1",
        company: "TechCorp Inc.",
        position: "Senior Software Developer",
        startDate: "2020-03",
        endDate: "Present",
        description: "Lead development of web applications using React, Node.js, and AWS. Mentored junior developers and implemented CI/CD pipelines.",
    },
    {
        id: "exp-2",
        company: "DesignStudio",
        position: "UI/UX Designer",
        startDate: "2019-06",
        endDate: "Present",
        description: "Created user-centered designs for mobile and web applications. Conducted user research and usability testing.",
    },
    {
        id: "exp-3",
        company: "CloudTech Solutions",
        position: "DevOps Engineer",
        startDate: "2018-09",
        endDate: "Present",
        description: "Managed cloud infrastructure on AWS and Azure. Implemented automated deployment pipelines and monitoring solutions.",
    },
    {
        id: "exp-4",
        company: "ProductCo",
        position: "Product Manager",
        startDate: "2021-01",
        endDate: "Present",
        description: "Led product development from ideation to launch. Worked closely with engineering and design teams to deliver user-focused features.",
    },
    {
        id: "exp-5",
        company: "DataInsights LLC",
        position: "Data Scientist",
        startDate: "2019-11",
        endDate: "Present",
        description: "Developed machine learning models for predictive analytics. Created data visualizations and reports for executive decision-making.",
    },
    {
        id: "exp-6",
        company: "MarketMasters",
        position: "Digital Marketing Specialist",
        startDate: "2020-07",
        endDate: "Present",
        description: "Managed digital marketing campaigns across multiple channels. Optimized SEO and PPC strategies to increase ROI.",
    },
    {
        id: "exp-7",
        company: "WebSolutions Pro",
        position: "Full-Stack Developer",
        startDate: "2019-04",
        endDate: "Present",
        description: "Built and maintained web applications using modern JavaScript frameworks. Collaborated with cross-functional teams.",
    },
    {
        id: "exp-8",
        company: "UserResearch Lab",
        position: "UX Researcher",
        startDate: "2020-02",
        endDate: "Present",
        description: "Conducted user research studies and analyzed user behavior patterns. Created personas and journey maps for product development.",
    },
    {
        id: "exp-9",
        company: "SecureNet Systems",
        position: "Cybersecurity Analyst",
        startDate: "2018-12",
        endDate: "Present",
        description: "Monitored network security and responded to security incidents. Implemented security policies and conducted vulnerability assessments.",
    },
    {
        id: "exp-10",
        company: "ProjectFlow Inc.",
        position: "Project Manager",
        startDate: "2019-08",
        endDate: "Present",
        description: "Managed software development projects using Agile methodologies. Coordinated between stakeholders and development teams.",
    },
    {
        id: "exp-11",
        company: "StartupXYZ",
        position: "Frontend Developer",
        startDate: "2017-05",
        endDate: "2019-02",
        description: "Developed responsive web interfaces using React and Vue.js. Worked in a fast-paced startup environment.",
    },
    {
        id: "exp-12",
        company: "BigTech Corp",
        position: "Software Engineer",
        startDate: "2016-08",
        endDate: "2019-05",
        description: "Contributed to large-scale web applications serving millions of users. Focused on performance optimization and scalability.",
    },
];

// Mock Educations Data
export const mockEducations: IEducation[] = [
    {
        id: "edu-1",
        school: "Massachusetts Institute of Technology",
        degree: "Bachelor of Science",
        field: "Computer Science",
        startDate: "2016-09",
        endDate: "2020-05",
    },
    {
        id: "edu-2",
        school: "Stanford University",
        degree: "Master of Fine Arts",
        field: "Design",
        startDate: "2015-09",
        endDate: "2017-06",
    },
    {
        id: "edu-3",
        school: "Carnegie Mellon University",
        degree: "Master of Science",
        field: "Information Systems Management",
        startDate: "2014-08",
        endDate: "2016-05",
    },
    {
        id: "edu-4",
        school: "University of California, Berkeley",
        degree: "Bachelor of Arts",
        field: "Business Administration",
        startDate: "2017-09",
        endDate: "2021-05",
    },
    {
        id: "edu-5",
        school: "Georgia Institute of Technology",
        degree: "Master of Science",
        field: "Analytics",
        startDate: "2015-08",
        endDate: "2017-05",
    },
    {
        id: "edu-6",
        school: "New York University",
        degree: "Bachelor of Science",
        field: "Marketing",
        startDate: "2018-09",
        endDate: "2022-05",
    },
    {
        id: "edu-7",
        school: "University of Washington",
        degree: "Bachelor of Science",
        field: "Computer Engineering",
        startDate: "2016-09",
        endDate: "2020-06",
    },
    {
        id: "edu-8",
        school: "University of Michigan",
        degree: "Master of Arts",
        field: "Human-Computer Interaction",
        startDate: "2014-09",
        endDate: "2016-04",
    },
    {
        id: "edu-9",
        school: "University of Texas at Austin",
        degree: "Bachelor of Science",
        field: "Information Security",
        startDate: "2017-08",
        endDate: "2021-05",
    },
    {
        id: "edu-10",
        school: "Columbia University",
        degree: "Master of Business Administration",
        field: "Technology Management",
        startDate: "2013-09",
        endDate: "2015-05",
    },
];

// Mock Gợi Ý AI Data
export const mockAISuggestions: IAISuggestion[] = [
    {
        id: "suggestion-1",
        type: EAISuggestionType.IMPROVEMENT,
        section: "summary",
        lineNumber: 1,
        message: "Consider adding more specific achievements and metrics to make your summary more impactful.",
        suggestion: "Add quantifiable achievements like 'Increased user engagement by 40%' or 'Reduced load times by 25%'.",
        applied: false,
    },
    {
        id: "suggestion-2",
        type: EAISuggestionType.WARNING,
        section: "experience",
        lineNumber: 3,
        message: "Job description is too generic and lacks specific accomplishments.",
        suggestion: "Replace generic descriptions with specific achievements and responsibilities.",
        applied: false,
    },
    {
        id: "suggestion-3",
        type: EAISuggestionType.WARNING,
        section: "education",
        lineNumber: 2,
        message: "Date format inconsistency detected.",
        suggestion: "Use consistent date format (MM/YYYY) throughout the CV.",
        applied: false,
    },
    {
        id: "suggestion-4",
        type: EAISuggestionType.IMPROVEMENT,
        section: "skills",
        lineNumber: 1,
        message: "Skills section could benefit from categorization.",
        suggestion: "Group skills into categories like 'Technical Skills', 'Soft Skills', and 'Tools & Technologies'.",
        applied: false,
    },
    {
        id: "suggestion-5",
        type: EAISuggestionType.WARNING,
        section: "experience",
        lineNumber: 5,
        message: "Action verbs could be more powerful.",
        suggestion: "Replace passive verbs with strong action verbs like 'Led', 'Developed', 'Implemented', 'Optimized'.",
        applied: false,
    },
    {
        id: "suggestion-6",
        type: EAISuggestionType.IMPROVEMENT,
        section: "summary",
        lineNumber: 2,
        message: "Consider tailoring summary to specific job applications.",
        suggestion: "Customize your summary to highlight skills and experiences most relevant to the target position.",
        applied: false,
    },
    {
        id: "suggestion-7",
        type: EAISuggestionType.WARNING,
        section: "contact",
        lineNumber: 1,
        message: "Missing professional email address.",
        suggestion: "Use a professional email address instead of personal email for job applications.",
        applied: false,
    },
    {
        id: "suggestion-8",
        type: EAISuggestionType.IMPROVEMENT,
        section: "experience",
        lineNumber: 7,
        message: "Consider quantifying your impact.",
        suggestion: "Include metrics and numbers to demonstrate the impact of your work (e.g., 'Managed a team of 5 developers').",
        applied: false,
    },
    {
        id: "suggestion-9",
        type: EAISuggestionType.WARNING,
        section: "skills",
        lineNumber: 3,
        message: "Skills list is too long and unfocused.",
        suggestion: "Prioritize the most relevant skills for your target role and keep the list to 10-15 key skills.",
        applied: false,
    },
    {
        id: "suggestion-10",
        type: EAISuggestionType.IMPROVEMENT,
        section: "education",
        lineNumber: 4,
        message: "Consider adding relevant coursework or projects.",
        suggestion: "Include relevant coursework, projects, or certifications that demonstrate your expertise.",
        applied: false,
    },
];

// Mock Job Description Results
export const mockJobDescriptionResults: IJobDescriptionResult[] = [
    {
        jobTitle: "Senior Frontend Developer",
        company: "TechCorp Inc.",
        jobLevel: "Senior",
        jobType: "Full-time",
        salary: "$120,000 - $150,000",
        location: "New York, NY (Remote)",
        responsibilities: [
            "Develop and maintain responsive web applications using React and TypeScript",
            "Collaborate with design team to implement pixel-perfect UI components",
            "Optimize application performance and user experience",
            "Mentor junior developers and conduct code reviews",
            "Participate in agile development processes and sprint planning"
        ],
        requirements: [
            "5+ years of experience in frontend development",
            "Expert knowledge of React, TypeScript, and modern JavaScript",
            "Experience with state management libraries (Redux, Zustand)",
            "Strong understanding of CSS, HTML, and responsive design",
            "Experience with testing frameworks (Jest, React Testing Library)"
        ],
        requiredSkills: ["React", "TypeScript", "JavaScript", "CSS", "HTML", "Redux", "Jest"],
        preferredSkills: ["Next.js", "GraphQL", "Tailwind CSS", "Figma", "Agile"],
        benefits: [
            "Competitive salary and equity package",
            "Health, dental, and vision insurance",
            "Flexible work arrangements",
            "Professional development budget",
            "401(k) matching"
        ]
    },
    {
        jobTitle: "UX/UI Designer",
        company: "DesignStudio",
        jobLevel: "Mid-level",
        jobType: "Full-time",
        salary: "$80,000 - $110,000",
        location: "San Francisco, CA",
        responsibilities: [
            "Create user-centered designs for web and mobile applications",
            "Conduct user research and usability testing",
            "Develop wireframes, prototypes, and high-fidelity mockups",
            "Collaborate with product and engineering teams",
            "Maintain and evolve design systems"
        ],
        requirements: [
            "3+ years of UX/UI design experience",
            "Proficiency in Figma, Sketch, or Adobe Creative Suite",
            "Strong portfolio demonstrating design process",
            "Experience with user research methodologies",
            "Understanding of design systems and component libraries"
        ],
        requiredSkills: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems"],
        preferredSkills: ["Principle", "InVision", "Miro", "Usability Testing", "Design Thinking"],
        benefits: [
            "Creative and collaborative work environment",
            "Health and wellness benefits",
            "Flexible PTO policy",
            "Professional development opportunities",
            "Catered meals and snacks"
        ]
    },
    {
        jobTitle: "DevOps Engineer",
        company: "CloudTech Solutions",
        jobLevel: "Senior",
        jobType: "Full-time",
        salary: "$130,000 - $160,000",
        location: "Austin, TX (Hybrid)",
        responsibilities: [
            "Design and maintain CI/CD pipelines",
            "Manage cloud infrastructure on AWS and Azure",
            "Implement monitoring and logging solutions",
            "Automate deployment and scaling processes",
            "Ensure system security and compliance"
        ],
        requirements: [
            "5+ years of DevOps or SRE experience",
            "Strong experience with AWS or Azure cloud platforms",
            "Proficiency in infrastructure as code (Terraform, CloudFormation)",
            "Experience with containerization (Docker, Kubernetes)",
            "Knowledge of monitoring tools (Prometheus, Grafana)"
        ],
        requiredSkills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Linux"],
        preferredSkills: ["Azure", "Jenkins", "Ansible", "Prometheus", "Python"],
        benefits: [
            "Competitive compensation package",
            "Comprehensive health benefits",
            "Remote work flexibility",
            "Learning and certification reimbursement",
            "Team building events"
        ]
    },
    {
        jobTitle: "Product Manager",
        company: "ProductCo",
        jobLevel: "Senior",
        jobType: "Full-time",
        salary: "$140,000 - $170,000",
        location: "Seattle, WA",
        responsibilities: [
            "Define product strategy and roadmap",
            "Work with engineering and design teams to deliver features",
            "Conduct market research and competitive analysis",
            "Manage product lifecycle from ideation to launch",
            "Analyze product metrics and user feedback"
        ],
        requirements: [
            "5+ years of product management experience",
            "Experience with agile development methodologies",
            "Strong analytical and problem-solving skills",
            "Excellent communication and leadership abilities",
            "Technical background preferred"
        ],
        requiredSkills: ["Product Strategy", "Agile", "Analytics", "User Research", "Roadmapping"],
        preferredSkills: ["SQL", "A/B Testing", "Data Analysis", "Technical Writing", "Stakeholder Management"],
        benefits: [
            "Equity participation",
            "Comprehensive benefits package",
            "Flexible work schedule",
            "Professional development budget",
            "Modern office facilities"
        ]
    },
    {
        jobTitle: "Data Scientist",
        company: "DataInsights LLC",
        jobLevel: "Mid-level",
        jobType: "Full-time",
        salary: "$100,000 - $130,000",
        location: "Chicago, IL",
        responsibilities: [
            "Develop and deploy machine learning models",
            "Analyze large datasets to extract insights",
            "Create data visualizations and reports",
            "Collaborate with business stakeholders",
            "Present findings to technical and non-technical audiences"
        ],
        requirements: [
            "3+ years of data science experience",
            "Strong programming skills in Python or R",
            "Experience with machine learning frameworks",
            "Knowledge of statistical analysis and modeling",
            "Familiarity with data visualization tools"
        ],
        requiredSkills: ["Python", "Machine Learning", "Statistics", "SQL", "Data Visualization"],
        preferredSkills: ["R", "TensorFlow", "PyTorch", "Tableau", "Spark"],
        benefits: [
            "Competitive salary and bonuses",
            "Health, dental, and vision coverage",
            "Retirement savings plan",
            "Conference attendance support",
            "Collaborative work environment"
        ]
    },
    {
        jobTitle: "Digital Marketing Specialist",
        company: "MarketMasters",
        jobLevel: "Mid-level",
        jobType: "Full-time",
        salary: "$70,000 - $90,000",
        location: "Boston, MA",
        responsibilities: [
            "Develop and execute digital marketing campaigns",
            "Manage PPC and SEO strategies",
            "Create engaging content for social media",
            "Analyze campaign performance and ROI",
            "Collaborate with creative and web teams"
        ],
        requirements: [
            "3+ years of digital marketing experience",
            "Experience with Google Ads and Analytics",
            "Knowledge of SEO best practices",
            "Social media marketing experience",
            "Strong analytical and creative skills"
        ],
        requiredSkills: ["Google Ads", "SEO", "Social Media", "Content Marketing", "Analytics"],
        preferredSkills: ["Facebook Ads", "HubSpot", "Canva", "Email Marketing", "Influencer Marketing"],
        benefits: [
            "Performance-based bonuses",
            "Health benefits",
            "Flexible work hours",
            "Professional development",
            "Creative work environment"
        ]
    },
    {
        jobTitle: "Full-Stack Developer",
        company: "WebSolutions Pro",
        jobLevel: "Senior",
        jobType: "Full-time",
        salary: "$110,000 - $140,000",
        location: "Miami, FL (Remote)",
        responsibilities: [
            "Develop full-stack web applications",
            "Design and implement RESTful APIs",
            "Build responsive frontend interfaces",
            "Optimize application performance",
            "Participate in code reviews and mentoring"
        ],
        requirements: [
            "4+ years of full-stack development experience",
            "Strong proficiency in JavaScript/TypeScript",
            "Experience with React and Node.js",
            "Knowledge of database design and SQL",
            "Understanding of RESTful API design"
        ],
        requiredSkills: ["JavaScript", "React", "Node.js", "SQL", "REST APIs"],
        preferredSkills: ["TypeScript", "MongoDB", "Express.js", "GraphQL", "AWS"],
        benefits: [
            "Competitive salary",
            "Remote work options",
            "Health insurance",
            "Paid time off",
            "Technology stipend"
        ]
    },
    {
        jobTitle: "UX Researcher",
        company: "UserResearch Lab",
        jobLevel: "Senior",
        jobType: "Full-time",
        salary: "$95,000 - $125,000",
        location: "Los Angeles, CA",
        responsibilities: [
            "Conduct user research studies and interviews",
            "Analyze user behavior and pain points",
            "Create personas and user journey maps",
            "Collaborate with design and product teams",
            "Present research findings and recommendations"
        ],
        requirements: [
            "4+ years of UX research experience",
            "Experience with various research methodologies",
            "Strong analytical and synthesis skills",
            "Excellent communication and presentation abilities",
            "Background in psychology or human factors preferred"
        ],
        requiredSkills: ["User Research", "Usability Testing", "Personas", "Journey Mapping", "Data Analysis"],
        preferredSkills: ["Qualitative Research", "Quantitative Research", "Survey Design", "A/B Testing", "Ethnography"],
        benefits: [
            "Research-focused environment",
            "Comprehensive benefits",
            "Professional development",
            "Flexible work arrangements",
            "Modern office space"
        ]
    },
    {
        jobTitle: "Cybersecurity Analyst",
        company: "SecureNet Systems",
        jobLevel: "Mid-level",
        jobType: "Full-time",
        salary: "$85,000 - $115,000",
        location: "Denver, CO",
        responsibilities: [
            "Monitor network security and threats",
            "Conduct security assessments and audits",
            "Respond to security incidents",
            "Implement security policies and procedures",
            "Stay updated on security trends and threats"
        ],
        requirements: [
            "3+ years of cybersecurity experience",
            "Knowledge of security frameworks and standards",
            "Experience with security tools and technologies",
            "Understanding of network security principles",
            "Strong analytical and problem-solving skills"
        ],
        requiredSkills: ["Network Security", "Threat Analysis", "Incident Response", "Security Auditing", "Risk Assessment"],
        preferredSkills: ["SIEM", "Firewalls", "Intrusion Detection", "Penetration Testing", "Compliance"],
        benefits: [
            "Security clearance opportunities",
            "Competitive compensation",
            "Health and retirement benefits",
            "Continuous training",
            "Stable work environment"
        ]
    },
    {
        jobTitle: "Project Manager",
        company: "ProjectFlow Inc.",
        jobLevel: "Senior",
        jobType: "Full-time",
        salary: "$105,000 - $135,000",
        location: "Portland, OR",
        responsibilities: [
            "Manage software development projects",
            "Coordinate between stakeholders and teams",
            "Create and maintain project plans",
            "Monitor project progress and budgets",
            "Facilitate communication and resolve issues"
        ],
        requirements: [
            "5+ years of project management experience",
            "PMP or similar certification preferred",
            "Experience with Agile and Scrum methodologies",
            "Strong leadership and communication skills",
            "Technical background in software development"
        ],
        requiredSkills: ["Project Management", "Agile", "Scrum", "Risk Management", "Stakeholder Management"],
        preferredSkills: ["PMP", "Jira", "Microsoft Project", "Budget Management", "Change Management"],
        benefits: [
            "Project management certification support",
            "Comprehensive benefits package",
            "Professional development",
            "Work-life balance",
            "Team-oriented culture"
        ]
    },
];

// Mock CVs Data
export const mockCVs: ICV[] = [
    {
        id: "cv-1",
        userId: "user-1",
        title: "Senior Software Developer CV",
        personalInfo: mockPersonalInfos[0],
        experiences: [mockExperiences[0], mockExperiences[10]],
        educations: [mockEducations[0]],
        skills: ["JavaScript", "React", "Node.js", "TypeScript", "AWS", "Docker", "MongoDB"],
        createdAt: "2024-01-15T10:30:00Z",
        updatedAt: "2024-01-20T14:45:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-2",
        userId: "user-2",
        title: "UI/UX Designer Portfolio",
        personalInfo: mockPersonalInfos[1],
        experiences: [mockExperiences[1]],
        educations: [mockEducations[1]],
        skills: ["Figma", "Sketch", "Adobe XD", "User Research", "Prototyping", "Design Systems"],
        createdAt: "2024-01-10T09:15:00Z",
        updatedAt: "2024-01-18T16:20:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-3",
        userId: "user-3",
        title: "DevOps Engineer Resume",
        personalInfo: mockPersonalInfos[2],
        experiences: [mockExperiences[2]],
        educations: [mockEducations[2]],
        skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Jenkins", "Linux", "Python"],
        createdAt: "2024-01-08T11:45:00Z",
        updatedAt: "2024-01-16T13:30:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-4",
        userId: "user-4",
        title: "Product Manager CV",
        personalInfo: mockPersonalInfos[3],
        experiences: [mockExperiences[3]],
        educations: [mockEducations[3]],
        skills: ["Product Strategy", "Agile", "User Research", "Data Analysis", "SQL", "A/B Testing"],
        createdAt: "2024-01-12T08:20:00Z",
        updatedAt: "2024-01-19T10:15:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-5",
        userId: "user-5",
        title: "Data Scientist Resume",
        personalInfo: mockPersonalInfos[4],
        experiences: [mockExperiences[4]],
        educations: [mockEducations[4]],
        skills: ["Python", "Machine Learning", "Statistics", "SQL", "Tableau", "TensorFlow", "R"],
        createdAt: "2024-01-05T14:10:00Z",
        updatedAt: "2024-01-14T12:25:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-6",
        userId: "user-6",
        title: "Digital Marketing Specialist CV",
        personalInfo: mockPersonalInfos[5],
        experiences: [mockExperiences[5]],
        educations: [mockEducations[5]],
        skills: ["Google Ads", "SEO", "Social Media", "Content Marketing", "Analytics", "HubSpot"],
        createdAt: "2024-01-03T16:40:00Z",
        updatedAt: "2024-01-13T09:50:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-7",
        userId: "user-7",
        title: "Full-Stack Developer Resume",
        personalInfo: mockPersonalInfos[6],
        experiences: [mockExperiences[6], mockExperiences[11]],
        educations: [mockEducations[6]],
        skills: ["JavaScript", "React", "Node.js", "TypeScript", "MongoDB", "Express.js", "GraphQL"],
        createdAt: "2024-01-07T13:25:00Z",
        updatedAt: "2024-01-17T15:35:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-8",
        userId: "user-8",
        title: "UX Researcher Portfolio",
        personalInfo: mockPersonalInfos[7],
        experiences: [mockExperiences[7]],
        educations: [mockEducations[7]],
        skills: ["User Research", "Usability Testing", "Personas", "Journey Mapping", "Survey Design"],
        createdAt: "2024-01-09T10:55:00Z",
        updatedAt: "2024-01-15T11:40:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-9",
        userId: "user-9",
        title: "Cybersecurity Analyst CV",
        personalInfo: mockPersonalInfos[8],
        experiences: [mockExperiences[8]],
        educations: [mockEducations[8]],
        skills: ["Network Security", "Threat Analysis", "Incident Response", "SIEM", "Firewalls"],
        createdAt: "2024-01-11T12:15:00Z",
        updatedAt: "2024-01-21T08:30:00Z",
        privacy: EPrivacy.PUBLIC,
    },
    {
        id: "cv-10",
        userId: "user-10",
        title: "Project Manager Resume",
        personalInfo: mockPersonalInfos[9],
        experiences: [mockExperiences[9]],
        educations: [mockEducations[9]],
        skills: ["Project Management", "Agile", "Scrum", "Jira", "Risk Management", "Stakeholder Management"],
        createdAt: "2024-01-04T15:50:00Z",
        updatedAt: "2024-01-12T14:20:00Z",
        privacy: EPrivacy.PUBLIC,
    },
];

export const mockStats = {
    totalVisitors: 12543,
    uniqueVisitors: 8742,
    pageViews: 45892,
    avgSessionDuration: "3m 42s",
    bounceRate: "32.4%",
    topPages: [
        { name: "Homepage", views: 12450 },
        { name: "Programs", views: 8765 },
        { name: "Jobs", views: 6543 },
        { name: "Contact", views: 4321 },
        { name: "FAQ", views: 3210 },
    ],
    recentActivity: [
        { id: 1, action: "New user registered", time: "2 min ago" },
        { id: 2, action: "Job application submitted", time: "15 min ago" },
        { id: 3, action: "Contact form submitted", time: "1 hour ago" },
        { id: 4, action: "New blog post published", time: "3 hours ago" },
    ],
};